library(ahp)
cameraAhp <- Load('C:/Users/user/Desktop/camera.ahp')
Calculate(cameraAhp)
print(cameraAhp, priority = function(x) x$sparent$priority["total", x$name])
Visualize(cameraAhp)
Analyze(cameraAhp)
AnalyzeTable(cameraAhp)
